#!/bin/bash

# Installing packages
sudo pacman -S bspwm sxhkd lightdm-gtk-greeter rxvt-unicode feh picom ttf-fira-code rofi htop
rm -rf ~/.config
# Creating update script
cp ./scripts/update ~/update
chmod +x ~/update
# Copying files
cp -R -rf ./dir/.config* ~/.config

cp -rf ./dir/.Xresources ~/.Xresources

# Making files executable
chmod +x ~/.config/bspwm/bspwmrc
chmod +x ~/.config/polybar/launch.sh

