#!/bin/bash

# Creating update script
cp ./scripts/update ~/update

# Creating directories
mkdir ~/.config
mkdir ~/.config/bspwm
mkdir ~/.config/sxhkd
mkdir ~/.config/picom
mkdir ~/.config/polybar

# sxhkd
cp ./config/sxhkdrc ~/.config/sxhkd/sxhkdrc

# bspwm
cp ./config/bspwm ~/.config/bspwm/bspwmrc
chmod +x ~/.config/bspwm/bspwmrc

# polybar

cp ./config/launch.sh ~/.config/polybar/launch.sh
chmod +x ~/.config/polybar/launch.sh
cp ~/.config/polybar/config/config ~/.config/polybar/config

# picom
cp ~/ ~/.config/picom/picom.conf
