#!/bin/bash
echo "Starting Update"
git clone https://github.com/demondave/arch.git /tmp/arch_update
mkdir ~/git
rm -r ~/git/arch
sudo chmod +x /tmp/arch_update/install
bash ~/tmp/arch_update/install
rm -r /tmp/arch_update
echo "Update Finished"
