#!/bin/bash
echo "Starting Update"
mkdir ~/git
rm -r ~/git/arch
git clone https://github.com/demondave/arch.git ~/git/arch
sudo chmod +x ~/git/arch/install
bash ~/git/arch/install
echo "Update Finished"
